# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 12:14
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twillo_sid', models.CharField(blank=True, max_length=100, null=True)),
                ('twillo_token', models.CharField(blank=True, max_length=100, null=True)),
                ('twillo_from_no', models.CharField(blank=True, max_length=100, null=True)),
                ('twillo_to_no', models.CharField(blank=True, max_length=100, null=True)),
                ('mailgun_api_url', models.URLField(blank=True, null=True)),
                ('mailgun_api_key', models.CharField(blank=True, max_length=100, null=True)),
                ('mailgun_from', models.CharField(blank=True, max_length=100, null=True)),
                ('mailgun_to', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('date_time', models.DateTimeField()),
                ('provider', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Em', 'Email'), ('Sm', 'SMS'), ('De', 'Desktop'), ('Mo', 'Mobile')], default='Em', max_length=2), size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
