# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-21 04:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initialized', models.BooleanField(default=False)),
                ('twillo_sid', models.CharField(blank=True, max_length=100, null=True)),
                ('twillo_token', models.CharField(blank=True, max_length=100, null=True)),
                ('twillo_from_no', models.CharField(blank=True, max_length=100, null=True)),
                ('twillo_to_no', models.CharField(blank=True, max_length=100, null=True)),
                ('mailgun_api_url', models.URLField(blank=True, null=True)),
                ('mailgun_api_key', models.CharField(blank=True, max_length=100, null=True)),
                ('mailgun_from', models.CharField(blank=True, max_length=100, null=True)),
                ('mailgun_to', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('date_time', models.DateTimeField()),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('email', models.BooleanField(default=False)),
                ('sms', models.BooleanField(default=False)),
                ('desktop', models.BooleanField(default=False)),
                ('mobile', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
