# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reminder',
            old_name='provider',
            new_name='notification',
        ),
        migrations.AddField(
            model_name='profile',
            name='initialized',
            field=models.BooleanField(default=False),
        ),
    ]
