# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-21 04:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='notification',
        ),
        migrations.AddField(
            model_name='reminder',
            name='desktop',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reminder',
            name='email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reminder',
            name='mobile',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reminder',
            name='sms',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Provider',
        ),
    ]
