# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 04:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0002_auto_20170504_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reminder',
            name='title',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
