# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-20 04:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0003_auto_20170509_1010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.BooleanField(default=False)),
                ('sms', models.BooleanField(default=False)),
                ('desktop', models.BooleanField(default=False)),
                ('mobile', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='reminder',
            name='notification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reminder.Provider'),
        ),
    ]
