# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 08:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0005_remove_reminder_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='initialized',
        ),
    ]
